### PR TITLE
Add support for JSON data update in addition to XML

### PR DESCRIPTION
**Pull request by silid**
JSON is supported natively in AS3 so the template should detect whether data is JSON or XML and process appropriately.

### CODE REVIEW

**Comment by silid** [comment]
Hold this one - it is failing on 2.07

**Comment by silid** [comment]
It seems that 2.07 sanitises the data and won't pass anything that doesn't start with a `<`

**Comment by silid** [comment]
I think this is now ready for review.
If the data is valid XML, is passed on as before, if it is not - an attempt is made to convert JSON to TemplateData XML.

**Comment by jesperstarkar** [comment]
We're doing exactly that: appending < and stripping in the template.

**Comment by jeansson** [comment]
Great feature, if and when it works, I support merging

**Pull request merged**
